// REVERSE INTEGER
/**
 * @param {number} x
 * @return {number}
 */
var reverse = function(x) {
    
    //  2,147,483,647

    let xcopy =x ;
    x= Math.abs(x);
    let rev =0;
    while(x>0)
    {
        let last = x %10;
        rev =(10*rev)+last;
        x =Math.floor(x/10);
    }

let limit = Math.pow(2,31);
// same as let limit = 2**31;
if(rev <-limit || rev> limit) return 0;


    return (xcopy<0)? -rev:rev;
};